### ISSUE TITLE
no access via http

### ISSUE THREAD

**Issue by hartwigm** [cdragon/TWCManager#35]
Hello 

i install your Manager on a new Raspi with  Bulleye Lite

When i start with `sudo -u twcmanager python -m TWCManager 

i get the following messages after a request to the ip:8080

Can someone help me?

Hartwig 

`15:23:47 🎮 HTTP     20 Serving at port: 8080
15:23:47 ⛽ Manager  20 TWC Manager starting as fake Master with id 7777 and sign 77
----------------------------------------
Exception occurred during processing of request from ('192.168.133.149', 50430)
Traceback (most recent call last):
  File "/usr/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/admin/TWCManager/lib/TWCManager/Control/HTTPControl.py", line 160, in __init__
    BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
  File "/usr/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/home/admin/TWCManager/lib/TWCManager/Control/HTTPControl.py", line 781, in do_GET
    page = self.template.render(vars(self))
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/admin/TWCManager/lib/TWCManager/Control/themes/Modern/main.html.j2", line 1, in top-level template code
    {% extends "master.html.j2" %}
  File "/home/admin/TWCManager/lib/TWCManager/Control/themes/Modern/master.html.j2", line 11, in top-level template code
    {% block content %}{% endblock %}
  File "/home/admin/TWCManager/lib/TWCManager/Control/themes/Modern/main.html.j2", line 306, in block 'content'
    <label for="chargeNowRate" class="form-label text-muted">Charge with <span class="text-dark font-weight-bold" id="{{ twcid }}_ampsVal">{{ ampsMin[0] }}</span> A</label>
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 1
`

**Comment by SamIAm789** [comment]
I've the same issue! Did you find a solution?
